[build]
  command = "npm run generate"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://hribal.site https://*.hribal.site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
